# Generated by Django 5.0.1 on 2024-01-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='to',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='drivers',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='CarRental',
        ),
    ]
