# Generated by Django 5.0.1 on 2024-01-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car_cities_preregistration_user_carrental_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='delivery_date',
        ),
    ]
